### ISSUE TITLE
libneurosim couldn't find libneurosim.so.0 and libpy3neurosim.so.0 in cmake

### ISSUE THREAD

**Issue by jianyongpi** [INCF/libneurosim#17]
The cmake command:
sudo cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/NEST  /home/pijy/Downloads/nest-simulator-2.18.0 -Dwith-python=3 -Dwith-libneurosim=ON -Dwith-mpi=ON -Dwith-boost=ON

but the result is " Use libneurosim     : No"

if I change the cmake command:
LIBNEURO=/usr/local sudo cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/NEST  /home/pijy/Downloads/nest-simulator-2.18.0 -Dwith-libneurosim=ON -DNEUROSIM_LIBRARY=$LIBNEURO/lib/libneurosim.so.0 -DPYNEUROSIM_LIBRARY=$LIBNEURO/lib/libpy3neurosim.so.0 -DLIBNEUROSIM_INCLUDE_DIR=$LIBNEURO/include
 -Dwith-mpi=ON -Dwith-python=3 -Dwith-boost=ON

and execute sudo make, the result is:
No rule to make target '/lib/libneurosim.so.0', needed by 'conngen/libconngen.so'.  Stop.
CMakeFiles/Makefile2:638: recipe for target 'conngen/CMakeFiles/conngen.dir/all' failed

so, how can I do?

**Comment by jougs** [comment]
This issue is of the form "cannot install NEST with libneurosim enabled" and should thus be reported in the [NEST issue tracker](https://github.com/nest/nest-simulator/issues), not here. This tracker is for issues in libneurosim.
