### ISSUE TITLE
automake insists on needing a `ChangeLog`

### ISSUE THREAD

**Issue by StefanBruens** [INCF/libneurosim#22]
See https://www.gnu.org/software/automake/manual/html_node/Strictness.html

To get around this, either set

`AM_INIT_AUTOMAKE([foreign])`  in configure.ac

or `AUTOMAKE_OPTIONS = foreign` in Makefile.am

This was also mentioned in #19

**Comment by NerdLab53** [comment]
Please check these, I have made the changes you asked for.

**Comment by mdjurfeldt** [comment]
This is fixed in commit 6d1044f4

Thank you
