### ISSUE TITLE
libpyneurosim py2/py3 generation

### ISSUE THREAD

**Issue by sanjayankur31** [INCF/libneurosim#7]
Given that py2 is going to be EOL shortly, and most people have begun migrating to py3, I was hoping to provide libpyneurosim libraries built for both py2 and py3. Currently, though, I don't know how to do this, since the shared object is called `libpyneurosim` and is installed in `%{_libdir}`, which usually expands to `/usr/lib{,64}/` So the newer shared object overwrites the older one. Would it perhaps be possible to generate two different shared objects---`libpy2neurosim` and `libpy3neurosim` maybe? Do these need to go into `%{_libdir}` too, or should they go to `python{2,x,3,x}/site-packages` as that wouldn't cause the conflict either.

**Comment by sanjayankur31** [comment]
@mdjurfeldt , @jougs - any ideas on how this should be done? I can always open a PR with the implementation. Please do let me know.

**Comment by mdjurfeldt** [comment]
Dear Ankur,

I think your suggestion to version the library is good and would appreciate
if you could prepare a pull request.

Can you then extend the autotools configuration framework to look for the
presence of both libraries and also make sure that the correct one is
loaded based on python version?

libpy2/3neurosim seems like good naming.

Can you make sure that a link with the old name is installed for backward
compatibility?

Best regards,
Mikael

Den ons 22 aug. 2018 09:57Ankur Sinha <notifications@github.com> skrev:

**Comment by sanjayankur31** [comment]
Sure. I'll look into it in the coming weeks. I'll symlink `libpyneurosim` to the py2 version for backward compatibility. Please assign the issue to me. Cheers!
